### ISSUE TITLE
clean_pandas.decrypt_series

### ISSUE THREAD

**Issue by gWareCoder** [awburgess/clean_pandas#6]
I am getting the following error when trying to decrypt.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-26-48c49735cf11> in <module>()
----> 1 test_df.clean_pandas.decrypt_series('some_id')

AttributeError: 'CleanPandas' object has no attribute 'decrypt_series'

**Comment by awburgess** [comment]
Thanks.  I'm currently updating that branch with PR #7.  I'm hoping to get this wrapped up this week.  The current master branch, which has a different method signature, will work but uses a ```clean_series``` method where you indicate the ```clean_type```.  The signature refactor is intended to change this completely.  

Please let me know if you are experiencing something different.  I ran the tests on ```master``` without issue.

**Comment by gWareCoder** [comment]
> Thanks. I'm currently updating that branch with PR #7. I'm hoping to get this wrapped up this week. The current master branch, which has a different method signature, will work but uses a `clean_series` method where you indicate the `clean_type`. The signature refactor is intended to change this completely.
> 
> Please let me know if you are experiencing something different. I ran the tests on `master` without issue.

I am using azure notebooks and i have loaded from the wheel

Collecting clean_pandas
  Downloading https://files.pythonhosted.org/packages/69/cc/322e42a8b418c55d91a4783c2b6613ccd59e7eb093cbd774c7c4a9811e69/clean_pandas-0.1.1-py3-none-any.whl

the tests show decrypt_series but it doesnt seem to work.   Encrypting works fine.

**Comment by awburgess** [comment]
Thanks!  I'll hop on all this as soon as I can.

**Comment by awburgess** [comment]
@gWareCoder I've merged the latest PR and have issued a new release at 1.0.0.  This is a breaking change as the method signatures have changed.

**Comment by gWareCoder** [comment]
> @gWareCoder I've merged the latest PR and have issued a new release at 1.0.0. This is a breaking change as the method signatures have changed.

Thanks,  i reloaded v 1.0.0 and now get a different error.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-61049a3abafc> in <module>()
----> 1 from clean_pandas import CleanPandas

~/anaconda3_501/lib/python3.6/site-packages/clean_pandas/__init__.py in <module>()
----> 1 from clean_pandas.clean_pandas import CleanPandas

~/anaconda3_501/lib/python3.6/site-packages/clean_pandas/clean_pandas.py in <module>()
     17 
     18 
---> 19 @pd.api.extensions.register_dataframe_accessor('clean_pandas')
     20 class CleanPandas:
     21     def __init__(self, pandas_object: Union[pd.DataFrame, pd.Series]):

AttributeError: module 'pandas.api' has no attribute 'extensions'

**Comment by awburgess** [comment]
I'll try to replicate this error.  At present, it installed fine on two local machines (one Linux, one Windows.)  Out of curiosity, did you do?:

```bash
pip uninstall clean_pandas
pip install clean_pandas
```

The error itself reads like a broken ```pandas``` installation or an older version (this is built using 0.23.4.)  Just confirming with the docs, [Pandas Extensions](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.api.extensions.register_dataframe_accessor.html), the ```extensions``` module should be available from the ```api``` module

**Comment by gWareCoder** [comment]
> I'll try to replicate this error. At present, it installed fine on two local machines (one Linux, one Windows.) Out of curiosity, did you do?:
> 
> ```shell
> pip uninstall clean_pandas
> pip install clean_pandas
> ```
> 
> The error itself reads like a broken `pandas` installation or an older version (this is built using 0.23.4.) Just confirming with the docs, [Pandas Extensions](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.api.extensions.register_dataframe_accessor.html), the `extensions` module should be available from the `api` module

Sorry bud,  still no luck running in Azure Notebooks.  I get the following still now when i try and import the library to a new cluster.  

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-61049a3abafc> in <module>()
----> 1 from clean_pandas import CleanPandas

~/anaconda3_501/lib/python3.6/site-packages/clean_pandas/__init__.py in <module>()
----> 1 from clean_pandas.clean_pandas import CleanPandas

~/anaconda3_501/lib/python3.6/site-packages/clean_pandas/clean_pandas.py in <module>()
     17 
     18 
---> 19 @pd.api.extensions.register_dataframe_accessor('clean_pandas')
     20 class CleanPandas:
     21     def __init__(self, pandas_object: Union[pd.DataFrame, pd.Series]):

AttributeError: module 'pandas.api' has no attribute 'extensions'

**Comment by gWareCoder** [comment]
Hi I was hoping you could perhaps make a docker container image for me of a working configuration?

**Comment by awburgess** [comment]
@gWareCoder You got it.  Sorry for delay in addressing this as I haven't had much time of late.  I should be able to commit more time to this over the next week or so.
